# Generated by Django 2.2 on 2019-05-13 11:38

import django.core.validators
from django.db import migrations, models


def convert_pages_to_percentage(apps, schema_editor):
    BookProgress = apps.get_model('books', 'BookProgress')
    progresses = BookProgress.objects.all()
    for progress in progresses:
        max_page = progress.book.page_count
        percent_progress = round(100 * (progress.pages_read / max_page))
        progress.percent_progress = percent_progress
        progress.save()


def convert_percentage_to_pages(apps, schema_editor):
    BookProgress = apps.get_model('books', 'BookProgress')
    progresses = BookProgress.objects.all()
    for progress in progresses:
        max_page = progress.book.page_count
        decimal_progress = progress.percent_progress / 100
        pages_read = round(max_page * decimal_progress)
        progress.pages_read = pages_read
        progress.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190421_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='percent_progress',
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name='Progress'),
        ),
        migrations.RunPython(convert_pages_to_percentage, convert_percentage_to_pages),
        migrations.RemoveField(
            model_name='bookprogress',
            name='pages_read',
        ),
    ]
